#!/usr/bin/env bash

set -e

directory="$HOME/docs/notes"
note_template="$HOME/docs/note-template.md"
terminal="${TERMINAL:=alacritty}"
editor="${EDITOR:=nvim}"

info="Usage:
  -d/--directory
  -t/--terminal
  -e/--editor
"

while [[ $# -gt 0 ]]
do
    echo "$1"
    case "$1" in
        -d|--directory)
            shift
            directory=$1
            [[ -d $directory ]] || echo "Directory '$directory' does not exists" && exit 1
            ;;
        -t|--terminal)
            shift
            terminal="$1"
            ;;
        -e|--editor)
            shift
            editor="$1"
            ;;
        --help|*)
            echo "$info"
            exit 1
            ;;
    esac
    shift
done
file_name="$directory/$(date --iso-8601=ns | grep -oP ".*:\d\d(?=,)").md"
cp "$note_template" "$file_name"
"$terminal" -e "$editor" "$file_name" || exit 1
