#!/bin/bash

set -e

configs="$HOME/.config/shell
$HOME/.config/nvim
$HOME/.config/vifm
$HOME/.config/ranger
$HOME/.config/zsh/.zshrc
$HOME/.local/share/nvim/plugged
$HOME/.config/blender/3.1/scripts
"

folder=$(echo "$configs" | dmenu -l 20)
# folder=$(echo "$configs" | fzf -0)
alacritty -e nvim "$folder"
