#!/bin/bash

set -e

version="v$(poetry version -s)"
echo "Release name: $version"

rm dist/*
poetry build
gh release create --generate-notes "$version"
gh release upload "$version" dist/*
twine upload dist/*
