#!/usr/bin/env python

import argparse
import datetime
import logging
import os
import re
from collections import UserList
from dataclasses import dataclass
from pprint import pprint

logger = logging.getLogger(__name__)


_DEFAULT_FILENAME = os.path.join(os.environ.get("HOME", "~/"), "docs/day.md")
_TIMETABLE_START = "# TIMETABLE START\n"
_TIMETABLE_END = "# TIMETABLE END\n"

ignore = [
    "^[#]+",  # annotations
    "^[\s]*$",  # empty lines
]


def _parse_line(line: str):
    if not re.search("[-\ ]*\d\d:\d\d .+", line):
        raise ValueError(line)
    numbers_part = re.search("\d\d:\d\d", line).group()
    numbers = re.findall("\d\d", numbers_part)
    title = re.search("(?<=\d\d) .*$", line).group()[1:]
    hour = int(numbers[0])
    minute = int(numbers[1])
    return hour, minute, title


@dataclass
class DisplayConfig:
    description: bool = True
    time: bool = True
    title: bool = True


@dataclass
class Activity:
    title: str
    start: datetime.time

    def __init__(self, line):
        hour, minute, title = _parse_line(line)
        self.title = title
        self.start = datetime.time(hour=hour, minute=minute)

    def display(self, display_config: DisplayConfig) -> str:
        result = ""
        if display_config.description:
            if display_config.time:
                result += f"start: {self.start}"
                if display_config.title:
                    result += " "
            if display_config.title:
                result += f"title: {self.title}"
        else:
            if display_config.time:
                result += f"{self.start}"
                if display_config.title:
                    result += " "
            if display_config.title:
                result += f"{self.title}"
        return result


class Timetable(UserList):
    def now(self) -> Activity:
        now = datetime.datetime.now().time()
        return self.for_datetime(now)

    def next(self) -> Activity:
        now = datetime.datetime.now().time()
        return self.for_datetime(now, 1)

    def for_datetime(self, datetime_obj, add: int = 0) -> Activity:
        activity = self.data[0]
        count = 0
        for x in self.data:
            if x.start >= datetime_obj:
                count += 1
                if count > add:
                    break
            activity = x
        return activity


def parse_file(timetable_filename) -> Timetable:
    timetable_lines = []
    with open(timetable_filename, "r", encoding="utf-8") as file:
        reading_timetable = False
        for line in file.readlines():
            # Ignore lines
            skip = False
            for expr in ignore:
                if re.match(expr, line):
                    logger.debug(expr)
                    skip = True
            if skip:
                if line != _TIMETABLE_END and line != _TIMETABLE_START:
                    logger.debug("Ignoring line '%s'", line)
                    continue

            # Timetable
            if reading_timetable:
                if line == _TIMETABLE_END:
                    reading_timetable = False
                else:
                    timetable_lines.append(line)
            if line == _TIMETABLE_START:
                reading_timetable = True

    timetable = [Activity(timetable_lines[-1])] + [
        Activity(line) for line in timetable_lines
    ]
    return Timetable(timetable)


def get_args():
    parser = argparse.ArgumentParser()

    # Config
    parser.add_argument("-t", "--timetable-file", type=str,
                        default=_DEFAULT_FILENAME)

    # Display options
    parser.add_argument("-T", "--no-time", action="store_true")
    parser.add_argument("-I", "--no-title", action="store_true")

    # Tasks to display
    parser.add_argument("-D", "--no-description", action="store_true")
    parser.add_argument("-C", "--no-current-task", action="store_true")
    parser.add_argument("-N", "--no-next-task", action="store_true")
    return parser.parse_args()


def main():
    config = get_args()
    display_config = DisplayConfig(
            time=not config.no_time,
            description=not config.no_description,
            title=not config.no_title)
    timetable = parse_file(config.timetable_file)
    if not config.no_current_task:
        line = ""
        if display_config.description:
            line += "Now: "
        line += timetable.now().display(display_config)
        print(line)
    if not config.no_next_task:
        line = ""
        if display_config.description:
            line += "Next: "
        line += timetable.next().display(display_config)
        print(line)


if __name__ == "__main__":
    main()
